name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set env
      run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

    - name: Print BASE_URL
      run: echo "BASE_URL is $BASE_URL"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease -PBASE_URL=${{ secrets.BASE_URL }}

    - name: Save APK artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Calculators
        path: artifacts/Calculators.apk
