name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 1.8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 1.8
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace

      - name: Save a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Calculators
          path: app/build/outputs/apk/release/app-release-unsigned.apk
