name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Load BASE_URL secret
      run: echo "::set-env name=BUILD_URL::${{ secrets.BASE_URL }}"
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Save APK artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Calculators
        path: artifacts/Calculators.apk
